spring:
  application:
    name: 'FundooNote'

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    least-renewal-interval-in-seconds: 10
    least-expiration-duration-in-seconds: 20


  client:
    service-url:
      defaultZone: http://localhost:8761/eureka